apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: php-hello-world-ingress
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - php-hello-world.apps.gusek.info
      secretName: wildcard-apps 
  rules:
    - host: php-hello-world.apps.gusek.info
      http:
        paths:
        - path: /
          backend:
            serviceName: php-hello-world-service
            servicePort: http