apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stuff
commonLabels:
  app: php_hello_world

resources:
- Deployment.yaml
- Service.yaml
- Ingress.yaml

images:
- name: php-hello-world-image
  newName: ghcr.io/stopdenbus/php_hello_world/hello_world
  newTag: c4a6a4a1e98e7f954a6e5060ab7ae26a8a8a39a2
