apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stuff
commonLabels:
  app: php_hello_world

resources:
- Deployment.yaml
- Service.yaml
- Ingress.yaml

images:
- name: php-hello-world-image
  newName: docker.pkg.github.com/stopdenbus/php_hello_world/hello_world
  newTag: 9a511ef13b050867f474fd65e99c6bf7c8d0d597
