name: create feature deployment
on:
  push:
    branches:
      - "feature/**"        
    types:
      - created
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "Hello World $GITHUB_REF_NAME"