name: create feature deployment
on:
  push:
    branches:
      - "feature/**"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump job github var
        if: ${{ github.created == true }}
        env:
          GITHUB_VAR: ${{ toJson(github) }}
        run: echo "$GITHUB_VAR"