name: Delete feature deployment
on: delete

jobs:
  delete-feature-deployment:
    if: ${{ (github.event.ref_type == 'branch') && (startsWith(github.event.ref, 'feature/')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: 'StopDenBus/helm-charts'
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: main
      - name: Delete feature deployment
        run: |
          yq 'del(.applications.php-hello-world.featureBranches.${{ github.event.ref }})' -i charts/applications/values.yaml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump chart version"
        
      - run: git push origin main
