name: Create or update feature deployment
on:
  push:
    branches:
      - "feature/**"
jobs:
  image-build-and-publish-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3 
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ github.sha }}

  create-or-update-feature-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: 'StopDenBus/helm-charts'
          token: ${{ secrets.DEPLOY_TOKEN }}
          ref: main

      - name: Create feature deployment
        run: |
          echo "set chart version to ${CHART_VERSION}"
          yq '.applications.php-hello-world.featureBranches.${{ github.ref_name }} = {"tag": "${{ github.sha }}"}' -i charts/applications/values.yaml 

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Bump chart version"
      
      - run: git push origin main

